import {
  Code2,
  Layout,
  Server,
  Database,
  Wrench,
  Brain,
  Shield,
  Terminal,
  Activity,
  TestTube,
} from "lucide-react";
export const techStack = [
  {
    title: "Programming Languages",
    icon: Code2,
    items: [
      "TypeScript",
      "JavaScript",
      "Python",
      "Go",
      "Java",
      "C/C++",
      "Bash",
      "Assembly",
    ],
    color: "#4B5563,#16a34a33",
  },
  {
    title: "Frontend",
    icon: Layout,
    items: [
      "React",
      "Next.js",
      "React Native (Expo)",
      "TailwindCSS",
      "Redux Toolkit",
      "Zustand",
      "TanStack Query",
    ],
    color: "#a855f733,#ca8a0433",
  },
  {
    title: "Backend",
    icon: Server,
    items: [
      "NestJS",
      "Express.js",
      "FastAPI",
      "Django",
      "Gin",
      "WebSockets",
      "REST",
      "GraphQL",
      "Socket.io",
    ],
    color: "#22c55e33",
  },
  {
    title: "Databases, Caching & ORMs",
    icon: Database,
    items: [
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Supabase",
      "Prisma",
      "TypeORM",
      "Drizzle",
      "Firebase",
      "SQL",
      "NoSQL",
    ],
    color: "#eab30833,#ca8a0433",
  },
  {
    title: "Infrastructure, Cloud & DevOps",
    icon: Wrench,
    items: [
      "Docker",
      "Nginx",
      "Traefik",
      "GitHub Actions",
      "Linux",
      "Coolify",
      "Cloudflare",
      "Azure",
      "DigitalOcean",
      "Vercel",
      "Git/GitHub",
    ],
    color: "#ef444433,#dc262633",
  },
  {
    title: "Observability",
    icon: Activity,
    items: ["Grafana", "Loki", "Tempo", "Mimir", "Uptime Kuma"],
    color: "#3b82f633,#2563eb33",
  },
  {
    title: "Testing",
    icon: TestTube,
    items: ["Jest", "Playwright", "Postman"],
    color: "#8b5cf633,#60a5fa33",
  },
  {
    title: "Security & Authentication",
    icon: Shield,
    items: [
      "BetterAuth",
      "OAuth2",
      "JWT",
      "Secure Cookies",
      "Network Security",
      "Penetration Testing",
      "Cryptography",
    ],
    color: "#10b98133,#05966933",
  },
  {
    title: "AI & ML",
    icon: Brain,
    items: [
      "OpenAI",
      "NumPy",
      "Pandas",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
    ],
    color: "#ec489933,#db277733",
  },
  {
    title: "Other Skills",
    icon: Terminal,
    items: [
      "CLI",
      "Web Scraping",
      "Automation",
      "OOP",
      "Figma",
      "Technical Writing",
    ],
    color: "#f9731633,ea580c33",
  },
];
