import {
    Code2,
    Layout,
    Server,
    Database,
    Wrench,
    Brain,
    Shield,
    Terminal,
  } from "lucide-react";
export const techStack = [
    {
      title: "Programming Languages",
      icon: Code2,
      items: [
        "C/C++",
        "Assembly",
        "Python",
        "JavaScript",
        "TypeScript",
        "Go",
        "Java",
        "Bash",
      ],
      color: "#4B5563",
    },
    {
      title: "Frontend",
      icon: Layout,
      items: [
        "React",
        "Next.js",
        "React Native",
        "TailwindCSS",
        "Redux",
        "Zustand",
        "React Query",
      ],
      color: "#a855f733",
    },
    {
      title: "Backend",
      icon: Server,
      items: ["Express.js", "Nest.js", "FastAPI", "Django", "Gin", "Socket.io"],
      color: "#22c55e33",
    },
    {
      title: "Database",
      icon: Database,
      items: [
        "Firebase",
        "Supabase",
        "TypeORM",
        "PrismaORM",
        "Mongoose",
        "SQL",
        "NoSQL",
        "Redis",
      ],
      color: "#eab30833",
    },
    {
      title: "DevOps & Tools",
      icon: Wrench,
      items: [
        "Git/GitHub",
        "GitHub Actions",
        "Docker",
        "Nginx",
        "DigitalOcean",
        "Azure",
        "VS Code",
      ],
      color: "#ef444433",
    },
    {
      title: "AI & ML",
      icon: Brain,
      items: [
        "OpenAI",
        "NumPy",
        "Pandas",
        "TensorFlow",
        "PyTorch",
        "Scikit-learn",
      ],
      color: "#ec489933",
    },
    {
      title: "Cybersecurity",
      icon: Shield,
      items: [
        "Network Security",
        "Penetration Testing",
        "Security Auditing",
        "Cryptography",
      ],
      color: "#10b98133",
    },
    {
      title: "Other Skills",
      icon: Terminal,
      items: [
        "Linux",
        "CLI",
        "Web Scraping",
        "Automation",
        "OOP",
        "Figma",
        "Technical Writing",
      ],
      color: "#f9731633",
    },
  ];