import {
    Code2,
    Layout,
    Server,
    Database,
    Wrench,
    Brain,
    Shield,
    Terminal,
  } from "lucide-react";
export const techStack = [
    {
      title: "Programming Languages",
      icon: Code2,
      items: [
        "C/C++",
        "Assembly",
        "Python",
        "JavaScript",
        "TypeScript",
        "Go",
        "Java",
        "Bash",
      ],
      color: "from-blue-500/20 to-blue-600/20",
    },
    {
      title: "Frontend",
      icon: Layout,
      items: [
        "React",
        "Next.js",
        "React Native",
        "TailwindCSS",
        "Redux",
        "Zustand",
        "React Query",
      ],
      color: "from-purple-500/20 to-purple-600/20",
    },
    {
      title: "Backend",
      icon: Server,
      items: ["Express.js", "Nest.js", "FastAPI", "Django", "Gin", "Socket.io"],
      color: "from-green-500/20 to-green-600/20",
    },
    {
      title: "Database",
      icon: Database,
      items: [
        "Firebase",
        "Supabase",
        "TypeORM",
        "PrismaORM",
        "Mongoose",
        "SQL",
        "NoSQL",
        "Redis",
      ],
      color: "from-yellow-500/20 to-yellow-600/20",
    },
    {
      title: "DevOps & Tools",
      icon: Wrench,
      items: [
        "Git/GitHub",
        "GitHub Actions",
        "Docker",
        "Nginx",
        "DigitalOcean",
        "Azure",
        "VS Code",
      ],
      color: "from-red-500/20 to-red-600/20",
    },
    {
      title: "AI & ML",
      icon: Brain,
      items: [
        "OpenAI",
        "NumPy",
        "Pandas",
        "TensorFlow",
        "PyTorch",
        "Scikit-learn",
      ],
      color: "from-pink-500/20 to-pink-600/20",
    },
    {
      title: "Cybersecurity",
      icon: Shield,
      items: [
        "Network Security",
        "Penetration Testing",
        "Security Auditing",
        "Cryptography",
      ],
      color: "from-emerald-500/20 to-emerald-600/20",
    },
    {
      title: "Other Skills",
      icon: Terminal,
      items: [
        "Linux",
        "CLI",
        "Web Scraping",
        "Automation",
        "OOP",
        "Figma",
        "Technical Writing",
      ],
      color: "from-orange-500/20 to-orange-600/20",
    },
  ];